// Details
export const REQUEST_MOVIE_DETAILS = 'REQUEST_MOVIE_DETAILS'
export const SUCCESS_MOVIE_DETAILS = 'SUCCESS_MOVIE_DETAILS'
export const FAILURE_MOVIE_DETAILS = 'FAILURE_MOVIE_DETAILS'

// List
export const REQUEST_MOVIE_LIST = 'REQUEST_MOVIE_LIST'
export const SUCCESS_MOVIE_LIST = 'SUCCESS_MOVIE_LIST'
export const FAILURE_MOVIE_LIST = 'FAILURE_MOVIE_LIST'

// SearchBar
export const REQUEST_SEARCH_MOVIE = 'REQUEST_SEARCH_MOVIE'
export const SUCCESS_SEARCH_MOVIE = 'SUCCESS_SEARCH_MOVIE'
export const FAILURE_SEARCH_MOVIE = 'FAILURE_SEARCH_MOVIE'
